import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const colors = {
  primary: '#6c5ce7',
  primaryLight: '#8677ed',
  lightPurple: '#e6e1fb',
  white: '#ffffff',
  black: '#333333',
  grey: '#f0f0f0',
  lightGrey: '#f8f8f8',
  darkGrey: '#a0a0a0',
  ongoing: '#f39c12',
  completed: '#2ecc71',
  pending: '#e74c3c',
  shadow: 'rgba(0, 0, 0, 0.1)',
};

export const styles = StyleSheet.create({
  // Main container with proper flex
  container: {
    flex: 1,
    backgroundColor: "#FDF5FF",
  },
  contentContainer: {
    flexGrow: 1,
  },
  // Header with improved styling
  header: {
   flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerText: {
    fontSize: 23,
    fontWeight: '600',
    color: '#000',
  },
  // Search container with better spacing
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: colors.white,
    borderRadius: 12,
    marginHorizontal: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.grey,
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  searchIcon: {
    marginRight: 4,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 8,
    marginLeft: 8,
    color: colors.black,
    fontSize: 15,
  },
  filterIcon: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.lightPurple,
  },
  // Filter chips section
  filterChipsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexGrow: 0,
    flexShrink: 0,
    flexDirection: 'row',
  },
  filterChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexGrow: 0,
    flexShrink: 0,
    marginBottom: 8,
    paddingHorizontal: 16,
    backgroundColor: "#FDF5FF"
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.lightPurple,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
    elevation: 1,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  filterChipText: {
    fontSize: 13,
    marginRight: 6,
    color: colors.primary,
    fontWeight: '500',
  },
  // Projects list with proper flex and scrolling
  projectsListContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  projectsContainer: {
    borderRadius: 12,
    padding: 3,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    flexGrow: 1,
  },
  emptyProjectsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyProjectsText: {
    fontSize: 16,
    color: "#000",
    fontWeight: '500',
    textAlign: 'center',
  },
  // Project item with enhanced styling and reduced vertical spacing
  projectItem: {
    backgroundColor: colors.white,
    padding: 14,
    marginVertical: 4, // Reduced from 6 to 4
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.grey,
    elevation: 5,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  projectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  projectName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
    flex: 1,
    marginRight: 8,
  },
  projectDepartment: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.black,
    marginTop: 6,
  },
  projectDate: {
    fontSize: 12,
    color: colors.darkGrey,
    textAlign: 'right',
  },
  DepDateContainer:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: colors.lightGrey,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  // Filter panel with proper sizing and animations
  filterPanel: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: width * 0.8,
    height: height,
    backgroundColor: colors.white,
    padding: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 20,
    shadowColor: colors.black,
    shadowOffset: { width: -3, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 10,
    zIndex: 100,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  filterScrollView: {
    flex: 1,
    // Make sure the content doesn't extend too close to the bottom
    paddingBottom: 20,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 12,
    color: colors.black,
  },
  checkboxRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  checkboxItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '45%',
    marginVertical: 6,
    marginRight: '5%',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: colors.darkGrey,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  checkboxLabel: {
    fontSize: 14,
    color: colors.black,
    flex: 1,
  },
  applyButtonContainer: {
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 30 : 16,
    borderTopWidth: 1,
    borderTopColor: colors.lightGrey,
    // Ensure this container is fully visible
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    paddingHorizontal: 20,
  },
  applyButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  applyButtonText: {
    color: colors.white,
    fontWeight: '600',
    fontSize: 16,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 50,
  },
  removeFiltersButton: {
    padding: 8,
  },
  removeFiltersText: {
    color: colors.primary,
    fontWeight: '500',
  },
});